name: education_on_cloud
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.5.3

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  video_player: ^2.9.1
  flick_video_player: ^0.9.0
  wakelock_plus: ^1.2.8
  smooth_page_indicator: ^1.2.0+3
  google_fonts: ^6.2.1
  country_flags: ^3.0.0
  get: ^4.6.6
  translator: ^1.0.0
  get_storage: ^2.1.1
  shared_preferences: ^2.3.2
  email_auth: ^2.0.0
  firebase_core: ^3.6.0
  mailer: ^6.2.0
  pinput: ^5.0.0
  firebase_messaging: ^15.1.3
  firebase_dynamic_links: ^6.0.8
  url_launcher: ^6.3.0
  carousel_slider: ^5.0.0
  stacked_card_carousel: ^0.0.4
  http: ^1.2.2
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib\Assets\Onboard\splashvideo.mp4
    - lib\Assets\Onboard\onboardfist.png
    - lib\Assets\Onboard\image.png
    - lib\Assets\Onboard\onboardsecond.png
    - lib\Views\Pages\Onboarding\onboardthird.png
    - lib\Assets\titlelogo.png
    - lib\Assets\indianflag.png
    - lib\Assets\Icons\book-icon-black.png
    - lib\Assets\Icons\home-icon-black.png
    - lib\Assets\Icons\person-icon-black.png
    - lib\Assets\Others\plan-img-eg.png
    - lib\Assets\Home\plan199.png
    - lib\Assets\Home\plan799.png
    - lib\Assets\Home\plan999.png
    - lib\Assets\Home\plan-effortless.png
    - lib\Assets\Home\statitics-bg.png
    - lib\Assets\Home\statitics-video.png
    - lib\Assets\Home\statitics-exam.png
    - lib\Assets\Home\statitics-graduate.png
    - lib\Assets\Home\statitics-google.png
    - lib\Assets\Others\studing-img.png
    - lib\Assets\Home\Category\cataimg-1.png
    - lib\Assets\Home\Category\cataimg-2.png
    - lib\Assets\Home\Category\cataimg-3.png
    - lib\Assets\Home\Category\cataimg-4.png
    - lib\Assets\Home\Category\cataimg-5.png
    - lib\Assets\Home\Category\cataimg-6.png
    - lib\Assets\Icons\arrow-circle-left.png
    - lib/Assets/Home/Course-session/west-bengal.png
    - lib/Assets/Home/Course-session/uttar-pradesh.png
    - lib/Assets/Home/Course-session/tamilnadu.png
    - lib/Assets/Home/Course-session/rajasthan-board.png
    - lib/Assets/Home/Course-session/punjab-board.png
    - lib/Assets/Home/Course-session/navodaya.png
    - lib/Assets/Home/Course-session/maharastra.png
    - lib/Assets/Home/Course-session/madhya-pradesh.png
    - lib/Assets/Home/Course-session/kendriyavidalaya.png
    - lib/Assets/Home/Course-session/karnataka.png
    - lib/Assets/Home/Course-session/icse-board.png
    - lib/Assets/Home/Course-session/haryana-board.png
    - lib/Assets/Home/Course-session/gujarat-board.png
    - lib/Assets/Home/Course-session/cbse-board.png
    - lib/Assets/Home/Course-session/andhra-pradesh.png
    - lib\Assets\Home\pro-feature-img.png
    - lib\Assets\Home\and-following-features-image.png
    - lib\Assets\Home\profile-image.png
    - lib\Assets\Flags\nepal-flag.png
    - lib\Assets\Flags\butan-flag.png
    - lib\Assets\Flags\bangladesh-flag.png
    - lib\Assets\Flags\srilanga-flag.png


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
